Repository hackmdio/codimd, pull requests merged in 2018-09, with the labels that each got.

#906 Fix possible weird objects as email
  lib/letter-avatars.js
Labels: bug

#936 Switch to own, fixed, lz-string version
  package.json
Labels: bug

#929 Add an auth provider guide for Mattermost
  README.md
  docs/guides/auth/mattermost-self-hosted.md
  docs/guides/images/auth/mattermost-enable-oauth2.png
  docs/guides/images/auth/mattermost-oauth-app-add.png
  docs/guides/images/auth/mattermost-oauth-app-done.png
  docs/guides/images/auth/mattermost-oauth-app-form.png
Labels: docs

#939 Extend migration error handling
  lib/migrations/20150702001020-update-to-0_3_1.js
  lib/migrations/20160112220142-note-add-lastchange.js
  lib/migrations/20160420180355-note-add-alias.js
  lib/migrations/20160515114000-user-add-tokens.js
  lib/migrations/20160607060246-support-revision.js
  lib/migrations/20160703062241-support-authorship.js
  lib/migrations/20161009040430-support-delete-note.js
  lib/migrations/20161201050312-support-email-signin.js
Labels: bug

#962 Add indonesian language to CodiMD
  app.js
  locales/id.json
  public/views/index/body.ejs
Labels: enhancement

#963 Fix server crash on PDF creation
  lib/response.js
Labels: bug, import/export

#967 Add POEditor to 'follow us' statement
  public/views/index/body.ejs
Labels: bug

#966 Fix document length limit on post
  lib/response.js
Labels: bug, security
