Repository hackmdio/codimd, pull requests merged in 2018-05, with the labels that each got.

#813 Workaround Google API problems
  app.js
  lib/config/default.js
  lib/config/environment.js
  public/views/hackmd/header.ejs
Labels: bug, security

#825 Removing google drive integration
  README.md
  app.js
  app.json
  public/js/google-drive-picker.js
  public/js/google-drive-upload.js
  public/js/index.js
  public/js/lib/common/constant.ejs
  public/js/lib/config/index.js
  public/js/lib/editor/ui-elements.js
  public/views/hackmd/header.ejs
  webpackBaseConfig.js
Labels: bug, security

#826 Upgrade base64url package
  package.json
Labels: security

#785 403: Redirect user to login page if not logged in
  lib/response.js
Labels: enhancement, untested
