Repository hackmdio/codimd, pull requests merged in 2018-07, with the labels that each got.

#884 Fix some night mode colors
  public/css/index.css
  public/css/markdown.css
  public/views/codimd/body.ejs
  public/views/index/body.ejs
Labels: bug

#883 Fixing content types in status router
  lib/web/statusRouter.js
Labels: bug

#886 Refactor generation of ToC
  public/css/extra.css
  public/vendor/md-toc.js
Labels: bug, refactor

#890 Add script src hash for speaker note to CSP directives
  lib/csp.js
Labels: bug

#896 Upload images to the filesystem by default, rather than to imgur
  lib/config/index.js
Labels: bug

#902 Support 'host' & 'path' config options
  README.md
  app.js
  lib/config/default.js
  lib/config/environment.js
Labels: enhancement

#907 Some minor improvements for LZString handling
  lib/history.js
  lib/models/note.js
Labels: enhancement

#894 Add missing catch blocks for migration from 1.1.1 to 1.2.0
  lib/migrations/20150702001020-update-to-0_3_1.js
  lib/migrations/20160112220142-note-add-lastchange.js
  lib/migrations/20160420180355-note-add-alias.js
  lib/migrations/20160515114000-user-add-tokens.js
  lib/migrations/20160607060246-support-revision.js
  lib/migrations/20160703062241-support-authorship.js
  lib/migrations/20161009040430-support-delete-note.js
  lib/migrations/20161201050312-support-email-signin.js
Labels: bug
