Repository hackmdio/codimd, pull requests merged in 2018-10, with the labels that each got.

#976 Some minor footer improvements
  public/views/index/body.ejs
Labels: enhancement

#977 Replace youtube example video on features page
  public/docs/features.md
Labels: bug

#979 Remove unused dependency
  package.json
Labels: enhancement

#968 Add documentation for an LDAP setup against Active Directory
  docs/guides/auth/ldap-AD.md
Labels: docs, enhancement

#932 Upgrade to Webpack 4
  .babelrc
  package.json
  public/views/includes/header.ejs
  public/views/includes/scripts.ejs
  webpack.config.js
  webpack.production.js
  webpackBaseConfig.js
  yarn.lock
Labels: enhancement

#958 Replace `uws` with `ws` package
  app.js
  package.json
Labels: bug

#974 fix image paths
  docs/guides/auth/gitlab-self-hosted.md
Labels: docs

#987 How to use Nextcloud as OAuth2 Provider for CodiMD
  docs/guides/auth/nextcloud.md
  docs/guides/images/auth/nextcloud-oauth2-1-settings.png
  docs/guides/images/auth/nextcloud-oauth2-2-client-add.png
  docs/guides/images/auth/nextcloud-oauth2-3-clientid-secret.png
Labels: docs

#981 Add development mode for webpack in package.json
  package.json
Labels: enhancement

#982 Add rel="noopener" to target="_blank" links
  public/js/extra.js
  public/views/codimd/body.ejs
  public/views/codimd/header.ejs
  public/views/index/body.ejs
  public/views/shared/refresh-modal.ejs
Labels: Hacktoberfest, enhancement, security

#940 enhance configurabiltiy of paths & make execution path-independent
  README.md
  app.js
  lib/config/default.js
  lib/config/index.js
  lib/models/revision.js
  lib/response.js
  lib/web/imageRouter/filesystem.js
  lib/web/statusRouter.js
Labels: enhancement

#942 Add OpenID to CodiMD
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/response.js
  lib/web/auth/index.js
  lib/web/auth/openid/index.js
  package.json
  public/views/shared/signin-modal.ejs
Labels: auth provider, feature

#992 Fix maintainer and URL in package.json
  package.json
Labels: docs

#1000 Fix #986 : Visibility is now transmitted with gitlab V4 api
  public/js/index.js
Labels: Hacktoberfest, bug

#1002 Fix #1001: get only project user is member of (and return max of results)
  lib/response.js
Labels: Hacktoberfest, enhancement

#990 Make oauth2 provider name accessible
  README.md
  lib/config/default.js
  lib/config/environment.js
Labels: bug

#993 Replace font-awesome with fork-awesome
  package.json
  public/views/codimd/head.ejs
  public/views/html.hbs
  public/views/index/head.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
  webpackBaseConfig.js
Labels: enhancement

#989 Remove dead package octicon
  package.json
  public/css/github-extract.css
  public/js/extra.js
  public/views/codimd/head.ejs
  public/views/html.hbs
  public/views/pretty.ejs
  public/views/slide.ejs
  webpack.common.js
Labels: Hacktoberfest, bug

#985 Add `data:` URL to CSP and upgrade helmet
  lib/csp.js
  package.json
Labels: Hacktoberfest, bug

#1004 Add autocomplete for highlight.js languages into codemirror
  public/js/index.js
Labels: enhancement

#1017 Fix #1016: webpack include defect for scripts and header files.
  package.json
  public/views/includes/header.ejs
  public/views/includes/scripts.ejs
  yarn.lock
Labels: Hacktoberfest, bug

#1018 Remove Gitter from codebase
  README.md
  locales/en.json
  public/docs/features.md
  public/views/shared/help-modal.ejs
Labels: enhancement

#1021 Webpack: Cleanup common config
  webpack.common.js
Labels: Hacktoberfest, enhancement

#1006 Fix not rendered autocomplete emojis
  public/js/extra.js
Labels: bug

#997 slide example: Add link to slide printing instructions
  public/docs/slide-example.md
Labels: docs

#1031 Fix emoji regex
  public/js/extra.js
Labels: bug

#1030 add option reset in bin/manage_users
  bin/manage_users
Labels: enhancement
