Repository hackmdio/codimd, pull requests merged in 2018-06, with the labels that each got.

#675 Add Azure Blob Storage support
  README.md
  config.json.example
  lib/config/default.js
  lib/config/dockerSecret.js
  lib/config/environment.js
  lib/config/index.js
  lib/web/imageRouter/azure.js
  package.json
Labels: feature

#782 Add title attribute in table of contents
  public/vendor/md-toc.js
Labels: enhancement

#783 Split authentication guides into multiple documents
  docs/guides/auth.md
  docs/guides/auth/github.md
  docs/guides/auth/gitlab-self-hosted.md
  docs/guides/auth/saml-onelogin.md
  docs/guides/auth/saml.md
  docs/guides/auth/twitter.md
Labels: auth provider, docs, enhancement

#784 Add "generic" OAuth2 support
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/migrations/20180326103000-use-text-in-tokens.js
  lib/models/user.js
  lib/response.js
  lib/web/auth/index.js
  lib/web/auth/oauth2/index.js
  public/views/index/body.ejs
  public/views/shared/signin-modal.ejs
Labels: auth provider, feature, untested

#836 Fix i18n writing locale files in production
  app.js
  lib/config/index.js
Labels: bug

#837 Add korean translation
  app.js
  locales/ko.json
  public/views/index/body.ejs
Labels: translation

#830 GDPR compliant part 1
  lib/migrations/20180525153000-user-add-delete-token.js
  lib/models/author.js
  lib/models/note.js
  lib/models/revision.js
  lib/models/user.js
  lib/realtime.js
  lib/response.js
  lib/web/userRouter.js
  locales/en.json
  package.json
  public/docs/privacy.md.example
  public/js/cover.js
  public/views/index/body.ejs
Labels: WIP, feature

#845 Move polyfill to CDN section
  public/views/hackmd/head.ejs
  public/views/index/head.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
Labels: bug

#844 Fix wrong docs about default image upload location
  README.md
Labels: docs

#846 Add a toolbar to Codemirror editor
  public/css/index.css
  public/js/index.js
  public/js/lib/editor/index.js
  public/js/lib/editor/toolbar.html
  public/js/lib/editor/utils.js
Labels: feature

#852 Remove unused zh.json from repo
  app.js
  locales/zh.json
Labels: enhancement

#853 Fix possible error if HackMD is started with wrong workdir
  README.md
  lib/config/default.js
  lib/config/index.js
  lib/web/imageRouter/index.js
Labels: bug

#858 Fix breaking regex
  lib/web/imageRouter/filesystem.js
Labels: bug

#857 Fix broken images in PDF caused by misconfigred server URL
  lib/response.js
Labels: bug

#856 Fix possible line-ending issues for init note
  lib/response.js
Labels: bug

#855 Move config out of statics path
  app.js
  lib/config/default.js
  lib/config/index.js
  lib/web/statusRouter.js
  public/views/includes/scripts.ejs
Labels: bug

#854 Allow to disable gravatar
  README.md
  lib/config/default.js
  lib/config/environment.js
  lib/letter-avatars.js
  lib/models/user.js
Labels: feature

#863 Add Print icon to slide view
  public/docs/slide-example.md
  public/js/slide.js
  public/views/slide.ejs
Labels: enhancement

#865 Fix broken unicode urls
  public/js/lib/config/index.js
Labels: bug

#868 Add docs for usage of terms and privacy policy
  docs/guides/providing-terms.md
Labels: docs

#871 Update dependencies
  lib/web/auth/ldap/index.js
  package.json
  public/js/history.js
  public/views/codimd/foot.ejs
  public/views/codimd/head.ejs
  public/views/html.hbs
  public/views/pretty.ejs
  public/views/slide.ejs
  webpackBaseConfig.js
Labels: enhancement
