Repository hackmdio/codimd, pull requests merged in 2018-03, with the labels that each got.

#750 Use ldap.usernameField over hardcoded uid fields
  README.md
  config.json.example
  lib/config/default.js
  lib/config/environment.js
  lib/web/auth/ldap/index.js
Labels: enhancement

#755 Remove unused LDAP option `tokenSecret`
  README.md
  config.json.example
  lib/config/default.js
  lib/config/environment.js
Labels: auth provider, bug

#756 Remove engine.io-client dependency
  package.json
  webpackBaseConfig.js
Labels: bug

#760 Multiple emails from LDAP are already an Array
  lib/web/auth/ldap/index.js
Labels: enhancement

#761 Add config option for report URI in CSP
  README.md
  lib/config/default.js
  lib/config/environment.js
  lib/csp.js
Labels: enhancement, security

#769 Add helper function to fix number problems
  lib/config/environment.js
  lib/config/utils.js
Labels: bug

#757 Add missing migration for permissions
  lib/migrations/20180306150303-fix-enum.js
Labels: bug, database/sequelize

#743 Fix to use url-safe base64 in note url
  lib/history.js
  lib/models/note.js
  lib/realtime.js
  lib/response.js
  package.json
  public/js/history.js
  public/js/utils.js
Labels: bug, refactor

#770 Add check for undefined UUID
  lib/web/auth/ldap/index.js
Labels: bug, security

#771 Refactoring imageRouter to modularity
  lib/config/index.js
  lib/web/imageRouter.js
  lib/web/imageRouter/filesystem.js
  lib/web/imageRouter/imgur.js
  lib/web/imageRouter/index.js
  lib/web/imageRouter/minio.js
  lib/web/imageRouter/s3.js
Labels: refactor

#772 Some fixes for inline-Attachments in Codemirror
  public/vendor/inlineAttachment/inline-attachment.js
Labels: bug, minor

#775 Persist nightmode so we can re-enable it on reload
  public/js/index.js
Labels: enhancement

#758 Change config to camel case with backwards compatibility
  README.md
  app.js
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/config/oldDefault.js
  lib/csp.js
  lib/models/index.js
  lib/models/note.js
  lib/ot/server.js
  lib/realtime.js
  lib/response.js
  lib/web/auth/dropbox/index.js
  lib/web/auth/email/index.js
  lib/web/auth/facebook/index.js
  lib/web/auth/github/index.js
  lib/web/auth/gitlab/index.js
  lib/web/auth/google/index.js
  lib/web/auth/index.js
  lib/web/auth/ldap/index.js
  lib/web/auth/mattermost/index.js
  lib/web/auth/saml/index.js
  lib/web/auth/twitter/index.js
  lib/web/imageRouter/filesystem.js
  lib/web/imageRouter/index.js
  lib/web/middleware/redirectWithoutTrailingSlashes.js
  lib/web/statusRouter.js
  public/views/hackmd/header.ejs
  public/views/shared/signin-modal.ejs
Labels: enhancement

#778 Fix night mode button after restore
  public/js/index.js
Labels: bug

#779 Allow embedding of video and audio tags
  lib/csp.js
Labels: bug, security

#788 Add documentation for setting up authentication with a self-hosted GitLab
  docs/guides/auth.md
  docs/guides/images/auth/gitlab-application-details.png
  docs/guides/images/auth/gitlab-new-application.png
  docs/guides/images/auth/gitlab-sign-in.png
Labels: docs

#786 Fix some issues with legacy config compatiblity
  lib/config/defaultSSL.js
  lib/config/index.js
Labels: bug

#780 Automatically generate a session secret if default is used
  lib/config/default.js
  lib/config/index.js
Labels: bug, security

#789 Add session data to env vars
  README.md
  app.json
  lib/config/environment.js
Labels: bug
