Repository hackmdio/codimd, pull requests merged in 2018-11, with the labels that each got.

#1034 Again: Replace emoji-plugin regex
  public/js/extra.js
Labels: bug

#1033 Upgrade some package versions
  package.json
Labels: enhancement, security

#991 Add full version string (and no AGPL violation detection)
  README.md
  app.js
  lib/config/environment.js
  lib/config/index.js
  lib/config/utils.js
  lib/realtime.js
  lib/web/statusRouter.js
  locales/en.json
  public/views/index/body.ejs
Labels: Hacktoberfest, discussion, enhancement

#961 Use OS based tmp dir
  lib/config/default.js
  tmp/.keep
Labels: enhancement

#1046 Remove the xss library from webpack
  public/js/render.js
  public/js/reveal-markdown.js
  webpack.common.js
Labels: enhancement

#1051 Fix wrong reading from commit
  lib/config/utils.js
Labels: bug

#1028 Add documentation about editor modes in features page
  public/docs/features.md
Labels: docs

#983 Enforce disabled index for static assets
  app.js
Labels: enhancement

#1027 Add download action to published notes
  lib/response.js
Labels: Hacktoberfest, enhancement

#1054 Fix logging in ot module
  lib/ot/editor-socketio-server.js
Labels: bug

#1047 Add documentation for document type
  public/docs/features.md
  public/docs/slide-example.md
  public/docs/yaml-metadata.md
Labels: docs

#1055 Upgrade winston / refactor logging
  README.md
  config.json.example
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/logger.js
  package.json
Labels: enhancement, refactor

#1057 switching to eslint for code checking
  .eslintignore
  .eslintrc.js
  README.md
  lib/models/index.js
  lib/models/user.js
  lib/realtime.js
  lib/web/imageRouter/filesystem.js
  package.json
  public/.eslintrc.js
  public/js/history.js
  public/js/index.js
  public/js/lib/editor/index.js
  public/js/lib/editor/ui-elements.js
Labels: enhancement

#1058 InternalOAuthError is not part of passport, but of passport-oauth2 #1056
  lib/web/auth/oauth2/index.js
Labels: bug

#1059 Fix streaming for winston
  app.js
  lib/logger.js
Labels: bug

#1040 Fix migration failure due to change on error messages
  lib/migrations/20150702001020-update-to-0_3_1.js
  lib/migrations/20160112220142-note-add-lastchange.js
  lib/migrations/20160420180355-note-add-alias.js
  lib/migrations/20160515114000-user-add-tokens.js
  lib/migrations/20160607060246-support-revision.js
  lib/migrations/20160703062241-support-authorship.js
  lib/migrations/20161009040430-support-delete-note.js
  lib/migrations/20161201050312-support-email-signin.js
Labels: enhancement

#943 Some minor improvements for setup script
  bin/setup
  package.json
Labels: enhancement

#1053 Disallow creation of robots.txt in freeurl
  README.md
  lib/config/default.js
  lib/config/environment.js
  lib/response.js
Labels: enhancement

#1060 Fixing links on index page
  public/views/index/body.ejs
Labels: bug

#1061 Add hints about how to be informed about updates
  README.md
Labels: docs

#1043 Fix ToC breaking documents with empty h* elements
  public/js/extra.js
  public/js/index.js
  public/vendor/md-toc.js
Labels: bug

#1065 Update reveal.js to version 3.7.0
  package.json
  public/views/slide.ejs
Labels: enhancement

#1066 Switch scrypt library to a successor
  lib/models/user.js
  package.json
Labels: enhancement

#1063 After removing ws, node version 10 should work
  .travis.yml
  package.json
Labels: enhancement

#1070 Fix typo in config.json.example
  config.json.example
Labels: bug

#1071 Remove node-uuid
  package.json
Labels: bug

#1069 Update from to-markdown to turndown
  package.json
  public/js/index.js
Labels: bug

#1072 Update doctoc to version 1.4.0
  package.json
Labels: enhancement
