Repository hackmdio/codimd, pull requests merged in 2018-02, with the labels that each got.

#725 Add referrer policy
  app.js
Labels: bug

#728 Fix to show 500 message when got error in parseNoteId
  lib/response.js
Labels: bug

#730 Update README.md
  README.md
Labels: enhancement

#735 Use jq instead of jsonlint
  .travis.yml
  package.json
Labels: bug, refactor

#739 Allow the usage of the esc-key by codemirror
  public/js/lib/editor/index.js
Labels: bug

#740 Extend HTML5 support by whitelisting various tags
  public/css/markdown.css
  public/js/render.js
Labels: enhancement
