Repository hackmdio/codimd, pull requests merged in 2019-01, with the labels that each got.

#1114 Update SAML to version 1.0.0
  package.json
Labels: bug, security

#1117 Update bootstrap from 3.3.7 to 3.4.0
  package.json
  public/views/codimd/foot.ejs
  public/views/codimd/head.ejs
  public/views/html.hbs
  public/views/index/foot.ejs
  public/views/index/head.ejs
  public/views/pretty.ejs
Labels: enhancement, security

#1116 Fix broken manage_users after Winston upgrade
  bin/manage_users
Labels: bug

#1121 Add tests for csp.js
  package.json
  test/csp.js
Labels: enhancement

#1123 Add linting for tests
  package.json
  test/letter-avatars.js
Labels: enhancement

#1124 Fix reference to SAML guide in README
  README.md
Labels: docs, enhancement

#1125 Fixing deep dependency problem with node 6.x
  package.json
Labels: bug
