Repository hackmdio/codimd, pull requests merged in 2019-03, with the labels that each got.

#1155 Mention dependency on libssl-dev in README.md
  README.md
Labels: docs

#1153 Fix empty serverURL did not redirect properly
  lib/response.js
Labels: bug

#1163 Add required change for Google+ API deprecation
  lib/web/auth/google/index.js
Labels: bug

#1131 Fix shown but broken GitLab snippets
  lib/config/index.js
Labels: bug

#1076 Add some missing translations
  locales/en.json
  public/views/index/body.ejs
  public/views/shared/signin-modal.ejs
Labels: bug

#1166 Fix broken HTML export with emojis
  public/js/extra.js
Labels: bug

#1158 Add serbian language
  app.js
  locales/sr.json
  public/views/index/body.ejs
Labels: feature
