Repository hackmdio/codimd, pull requests merged in 2020-07, with the labels that each got.

#1471 Feature/fretboard finish view
  public/js/extra.js
  public/js/index.js
  public/js/lib/renderer/fretboard/css/i.css
  public/js/lib/renderer/fretboard/fretboard.js
  public/js/lib/renderer/fretboard/svg/dot.svg
  public/js/lib/renderer/fretboard/svg/dotEmpty.svg
  public/js/lib/renderer/fretboard/svg/dotEmpty_h.svg
  public/js/lib/renderer/fretboard/svg/dotWideLeft.svg
  public/js/lib/renderer/fretboard/svg/dotWideMiddle.svg
  public/js/lib/renderer/fretboard/svg/dotWideRight.svg
  public/js/lib/renderer/fretboard/svg/dot_h.svg
  public/js/lib/renderer/fretboard/svg/fretb_horiz_5.svg
  public/js/lib/renderer/fretboard/svg/fretb_horiz_6.svg
  public/js/lib/renderer/fretboard/svg/fretb_horiz_7.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_12.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_15.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_4.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_5.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_7.svg
  public/js/lib/renderer/fretboard/svg/fretb_vert_9.svg
  public/js/lib/renderer/fretboard/svg/number1.svg
  public/js/lib/renderer/fretboard/svg/number1_h.svg
  public/js/lib/renderer/fretboard/svg/number2.svg
  public/js/lib/renderer/fretboard/svg/number2_h.svg
  public/js/lib/renderer/fretboard/svg/number3.svg
  public/js/lib/renderer/fretboard/svg/number3_h.svg
  public/js/lib/renderer/fretboard/svg/number4.svg
  public/js/lib/renderer/fretboard/svg/number4_h.svg
  public/js/lib/renderer/fretboard/svg/number5.svg
  public/js/lib/renderer/fretboard/svg/number5_h.svg
  public/js/lib/renderer/fretboard/svg/number6.svg
  public/js/lib/renderer/fretboard/svg/number6_h.svg
  public/js/lib/renderer/fretboard/svg/number7.svg
  public/js/lib/renderer/fretboard/svg/number7_h.svg
  public/js/lib/renderer/fretboard/svg/number8.svg
  public/js/lib/renderer/fretboard/svg/number8_h.svg
  public/js/lib/renderer/fretboard/svg/number9.svg
  public/js/lib/renderer/fretboard/svg/number9_h.svg
  public/js/lib/renderer/fretboard/svg/string_o.svg
  public/js/lib/renderer/fretboard/svg/string_x.svg
  webpack.common.js
Labels: markdown

#1505 Use array for tags when available (close #1496)
  lib/models/note.js
Labels: markdown

#1483 Support mindmap
  app.js
  package-lock.json
  package.json
  public/css/extra.css
  public/css/slide.css
  public/js/extra.js
  public/js/index.js
  public/js/lib/editor/index.js
Labels: markdown

#1463 Simple image lightbox
  public/js/extra.js
  public/js/lib/renderer/lightbox/index.js
  public/js/lib/renderer/lightbox/lightbox.css
  public/js/lib/syncscroll.js
Labels: enhancement, renderer

#1506 Implement csvpreview renderer
  package-lock.json
  package.json
  public/docs/features.md
  public/js/extra.js
  public/js/lib/renderer/csvpreview.js
  public/js/lib/syncscroll.js
Labels: markdown, renderer

#1498 Update Simplified Chinese translation and fix typography
  locales/zh-CN.json
  public/views/index/body.ejs
Labels: translation

#1546 feature: pass-through yaml metadata image to html meta tag
  lib/note/index.js
  public/docs/yaml-metadata.md
  public/views/pretty.ejs
Labels: yaml-metadata

#1551 Fix webpack urlpath font loading error
  public/css/font.css
  public/js/lib/editor/markdown-lint/index.js
  public/markdown-lint/css/lint.css
  public/markdown-lint/images/mark-error.png
  public/markdown-lint/images/mark-multiple.png
  public/markdown-lint/images/mark-warning.png
  public/markdown-lint/images/message-error.png
  public/markdown-lint/images/message-warning.png
  public/views/codimd/head.ejs
  public/views/includes/scripts.ejs
  public/views/index/head.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
  webpack.common.js
Labels: bug

#1548 List-my-note API
  .gitignore
  lib/auth/gitlab/index.js
  lib/history/index.js
  lib/note/index.js
  lib/routes.js
  public/js/extra.js
  public/js/index.js
  public/js/lib/editor/constants.js
  public/js/lib/editor/index.js
  public/js/lib/editor/spellcheck.js
  public/js/lib/markdown/utils.js
  public/js/render.js
  test/realtime/dirtyNoteUpdate.test.js
  utils/string.js
Labels: api
